import axios from "axios";
import { dataIntegrationService } from './dataIntegration';
import type { ChatResponse, ChatMessage, QueryIntent, DataResult, Entity } from '../types';

const OPENROUTER_API_KEY = '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';
const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
const GEMINI_MODEL = 'google/gemini-2.0-flash-lite-001';

const determineIntent = (prompt: string): QueryIntent | null => {
    const lowerQuery = prompt.toLowerCase();

    if (lowerQuery.includes("report")) {
        return { entity: 'report', type: 'generate' };
    }
    if (lowerQuery.includes("health") || lowerQuery.includes("medication") || lowerQuery.includes("allergy")) {
        return { entity: 'health', type: 'analyze' };
    }
    if (lowerQuery.includes("calendar") || lowerQuery.includes("schedule") || lowerQuery.includes("booking") || lowerQuery.includes("tour")) {
        return { entity: 'schedule', type: 'analyze' };
    }
    if (lowerQuery.includes("media") || lowerQuery.includes("photo") || lowerQuery.includes("picture") || lowerQuery.includes("video")) {
        return { entity: 'media', type: 'analyze' };
    }
    if (lowerQuery.includes("staff") || lowerQuery.includes("teacher") || lowerQuery.includes("shift")) {
        return { entity: 'staff', type: 'analyze' };
    }
    if (lowerQuery.includes("children") || lowerQuery.includes("enrollment") || lowerQuery.includes("student")) {
        return { entity: 'children', type: 'analyze' };
    }
    if (lowerQuery.includes("attendance")) {
        return { entity: 'attendance', type: 'analyze', timeframe: 'today' };
    }
    if (lowerQuery.includes("billing") || lowerQuery.includes("payment") || lowerQuery.includes("revenue")) {
        return { entity: 'billing', type: 'analyze' };
    }

    return null;
};

const formatResponse = (intent: QueryIntent, result: DataResult): Pick<ChatResponse, 'answer' | 'suggestions' | 'sources'> => {
    const providerPrefix = `(Local DB)`;
    const { data } = result;

    switch (intent.entity) {
        case 'report':
            return {
                answer: `${providerPrefix} Here is the comprehensive daily report you requested:

### 📈 **Overall Summary**
- **${data.totalChildren}** children enrolled.
- **${data.presentToday} / ${data.totalAttendanceRecords}** children present today.
- **$${data.totalRevenue.toLocaleString()}** in total revenue this month.
- **${data.totalStaff}** total staff members.
- **${data.highPriorityAlerts}** high-priority health alerts.
- **${data.upcomingEvents}** upcoming events on the schedule.

### 📊 **Today's Attendance**
- **Present:** ${data.presentToday}
- **Absent:** ${data.absentToday}

### ❤️ **Health & Safety**
- **High-Severity Alerts:** ${data.highPriorityAlerts}
- **Medications Due Today:** ${data.medicationsDue}

### 💰 **Monthly Billing Overview**
- **Total Revenue:** $${data.totalRevenue.toLocaleString()}
- **Outstanding Invoices:** ${data.outstandingInvoices}

### 🗓️ **Schedule**
- **Today's Events:** ${data.todayEventsCount}
- **Upcoming Tours:** ${data.upcomingTours}

This report was generated by combining data from all available sources.`,
                suggestions: ["Email this report to administration", "Show me the high-priority health alerts", "Which classrooms are fully staffed today?"],
                sources: ["Children API", "Attendance API", "Billing API", "Staff API", "Health API", "Schedule API"],
            };
        case 'health':
            return {
                answer: `${providerPrefix} Here is a summary of the health records:

❤️ **Health Overview:**
- **${data.totalRecords}** total health records on file.
- **${data.highPriority}** high-priority alerts (severe allergies, critical medications).
- **${data.allergies}** children with allergies noted.
- **${data.medications}** children requiring medication.

Would you like to see a specific child's record or a list of all high-priority alerts?`,
                suggestions: ["List all high-severity health alerts", "Which children have nut allergies?", "Show me today's medication schedule"],
                sources: ["Health API"],
            };
        case 'schedule':
             return {
                answer: `${providerPrefix} Here is an overview of the schedule:

🗓️ **Schedule & Bookings:**
- **${data.todayEvents.length}** events scheduled for today.
- **${data.tours}** upcoming tours booked.

**Up next:**
${data.upcoming.map((e: any) => `- ${e.event} at ${new Date(e.time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`).join("\n")}

Do you need to book a new tour or see the full calendar for the week?`,
                suggestions: ["Show me the full schedule for this week", "Book a new parent tour", "Are there any schedule conflicts?"],
                sources: ["Schedule API"],
            };
        case 'media':
            return {
                answer: `${providerPrefix} Here is a summary of the media library:

🖼️ **Media Overview:**
- **${data.total}** total media files uploaded.
- **${data.photos}** photos.
- **${data.videos}** videos.

**Recently Added:**
${data.recent.map((m: any) => `- ${m.type} in ${m.classroom} classroom on ${new Date(m.timestamp).toLocaleDateString()}`).join("\n")}

Would you like to see media for a specific classroom or child?`,
                suggestions: ["Show me photos from the Toddler room", "Upload a new video", "How many photos were added this week?"],
                sources: ["Media API"],
            };
        case 'staff':
            return {
                answer: `${providerPrefix} 👥 **Staff & Shift Overview:**
- **${data.total}** total staff members.
- **${data.onDuty}** staff currently on shift.
- **${data.teachers}** are certified teachers.

Would you like to see the full shift schedule for today or check staff certifications?`,
                suggestions: ["Show me today's full shift schedule", "Who is closing today?", "Generate a full daily report"],
                sources: ["Staff API"],
            };
        case 'children':
            return {
                answer: `${providerPrefix} Here’s an overview of enrolled children:

👶 **Enrollment Summary:**
- **${data.total}** total children enrolled.

**Recent Enrollments:**
${data.recent.map((c: any) => `- ${c.name} (${c.age} years old)`).join("\n")}

Would you like details about a specific child or a full classroom roster?`,
                suggestions: ["Show me the preschool classroom roster", "Generate a comprehensive daily report", "Any children with birthdays this month?"],
                sources: ["Enrollment API"],
            };
        case 'attendance':
            return {
                answer: `${providerPrefix} 📊 **Today's Attendance Summary:**
- **${data.present}** children are present.
- **${data.absent}** children are absent.
- **${data.total}** total attendance records for today.

Would you like me to generate a detailed weekly attendance report?`,
                suggestions: ["Show attendance by classroom", "List children with frequent absences", "Generate weekly report"],
                sources: ["Attendance API"],
            };
        case 'billing':
            return {
                answer: `${providerPrefix} 💰 **Billing Summary:**
- **$${data.revenue.toLocaleString()}** total revenue this month.
- **${data.outstanding}** outstanding (unpaid) invoices.

Would you like a breakdown of overdue accounts or a full financial report?`,
                suggestions: ["Show overdue accounts", "Generate monthly revenue report", "Send payment reminders"],
                sources: ["Billing API"],
            };
        default:
             return {
                answer: `${providerPrefix} I found some information, but I'm not sure how to display it for the entity '${intent.entity}'.`,
                suggestions: ["Try rephrasing your question", "Ask for a full report"],
                sources: ["Local DB"],
            };
    }
};

const query = async (prompt: string, provider: 'gemini' | 'openrouter', history: ChatMessage[] = []): Promise<ChatResponse> => {
    const intent = determineIntent(prompt);

    if (intent) {
        try {
            console.log(`🔍 Matched local intent: ${intent.entity} (${intent.type})`);
            const result = await dataIntegrationService.fetchData(intent);
            const formattedResponse = formatResponse(intent, result);

            return {
                ...formattedResponse,
                timestamp: new Date(),
                confidence: 0.98,
            };
        } catch (error) {
            console.error(`❌ Error handling local intent '${intent.entity}':`, error);
            return {
                answer: `(Local DB) I'm sorry, I encountered an error while processing your request for ${intent.entity} data. Please try again later.`,
                confidence: 0.3,
                timestamp: new Date(),
                sources: ["Local Data Error"],
                suggestions: ["Check the console for errors", "Try a different query"],
            };
        }
    }

    // Default fallback to AI model
    try {
        console.log(`Query does not match local API. Forwarding to ${provider} with history...`);

        const systemPrompt = `You are Sparky, an expert AI assistant for a childcare management system. Your goal is to be helpful, concise, and friendly, leveraging conversation history for context.
- Analyze the user's query and the provided chat history.
- Provide a clear, well-formatted answer in markdown.
- Your entire response MUST be a single JSON object with two keys: "answer" (a string containing your response) and "suggestions" (an array of 2-3 relevant, insightful follow-up questions the user might ask).
- Example format: {"answer": "Here is the information you requested.", "suggestions": ["Can you break this down by classroom?", "Email this to the director."]}
- If a user asks a general question, you can proactively offer to generate a detailed report for them based on the data you can access (enrollment, attendance, billing, staff, health, media, schedule).
- Do NOT add any text outside of the JSON object.`;
        
        const historyMessages = history.map(msg => ({
            role: msg.role,
            content: msg.content
        }));

        const response = await axios.post(
            OPENROUTER_API_URL,
            {
                model: GEMINI_MODEL,
                messages: [
                    { role: "system", content: systemPrompt },
                    ...historyMessages,
                    { role: "user", content: prompt }
                ],
                response_format: { type: "json_object" } // Request JSON output
            },
            {
                headers: {
                    'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
                    'Content-Type': 'application/json',
                    'HTTP-Referer': 'http://localhost:3000', 
                    'X-Title': 'Gemini Childcare Assistant' 
                }
            }
        );

        let parsedResponse;
        try {
            parsedResponse = JSON.parse(response.data.choices[0].message.content);
        } catch (e) {
            console.error("Failed to parse JSON from AI response:", e);
            return {
                answer: response.data.choices[0].message.content,
                confidence: 0.80,
                sources: [`${provider.charAt(0).toUpperCase() + provider.slice(1)} AI`],
                suggestions: ["Tell me a fun fact about child development", "Suggest a craft activity for preschoolers"],
                timestamp: new Date(),
            };
        }

        return {
            answer: parsedResponse.answer || "I received a response, but it was empty.",
            confidence: 0.85,
            sources: [`${provider.charAt(0).toUpperCase() + provider.slice(1)} AI`],
            suggestions: parsedResponse.suggestions || ["Ask another question", "Generate a daily report"],
            timestamp: new Date(),
        };

    } catch (error: any) {
        console.error(`Error calling OpenRouter API:`, error.response?.data || error.message);
        return {
            answer: `I'm having trouble connecting to the AI model right now. Please check the API key and endpoint configuration.`,
            confidence: 0.2,
            sources: ["OpenRouter API Error"],
            suggestions: ["Try asking a data-specific question", "Check the console for errors"],
            timestamp: new Date(),
        };
    }
};

export const chatService = {
  queryWithGemini: (prompt: string, userId: string, history: ChatMessage[]): Promise<ChatResponse> => {
    return query(prompt, 'gemini', history);
  },
  queryWithOpenRouter: (prompt: string, userId: string, history: ChatMessage[]): Promise<ChatResponse> => {
    return query(prompt, 'openrouter', history);
  },
  clearHistory: (userId: string): void => {
    console.log(`Chat history cleared for user ${userId}`);
  },
};
